# Generated by Django 3.2.20 on 2024-10-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
    ]
